@echo off

set ANDROID_STUDIO_LOCATION=C:\Program Files\Android\Android Studio
set ANDROID_SDK_LOCATION=%HOMEDRIVE%%HOMEPATH%\AppData\Local\Android\Sdk
set ANDROID_NDK_LOCATION=%ANDROID_SDK_LOCATION%\ndk
set ANDROID_NDK_VERSION=21.3.6528147
set ANDROID_CMAKE_LOCATION=%ANDROID_SDK_LOCATION%\cmake
set ANDROID_CMAKE_VERSION=3.10.2.4988404
set ANDROID_CMDLINE_TOOLS_LOCATION=%ANDROID_SDK_LOCATION%\cmdline-tools
set ANDROID_CMDLINE_TOOLS_VERSION=latest

set ANDROID_JAVA=%ANDROID_STUDIO_LOCATION%\jre
set ANDROID_JAVA_BIN=%ANDROID_JAVA%\bin
set ANDROID_SDK_TOOLS_PATH=%ANDROID_CMDLINE_TOOLS_LOCATION%\%ANDROID_CMDLINE_TOOLS_VERSION%\bin
if not exist "%ANDROID_SDK_TOOLS_PATH%" (
  set ANDROID_SDK_TOOLS_PATH=%ANDROID_SDK_LOCATION%\tools\bin
)
set ANDROID_SDK_PLATFORM_TOOLS_PATH=%ANDROID_SDK_LOCATION%\platform-tools
set ANDROID_NDK_PATH=%ANDROID_NDK_LOCATION%\%ANDROID_NDK_VERSION%
set ANDROID_CMAKE_PATH=%ANDROID_CMAKE_LOCATION%\%ANDROID_CMAKE_VERSION%\bin
title Android SDK Tools
set PATH=%ANDROID_JAVA_BIN%;%ANDROID_SDK_TOOLS_PATH%;%ANDROID_SDK_PLATFORM_TOOLS_PATH%;%ANDROID_NDK_PATH%;%ANDROID_CMAKE_PATH%;%PATH%

set JAVA_HOME=%ANDROID_JAVA%
set ANDROID_HOME=%ANDROID_SDK_LOCATION%
set ANDROID_NDK_HOME=%ANDROID_NDK_PATH%
set ANDROID_NDK=%ANDROID_NDK_PATH%

if /i not "%1" == "call" (
  cls
  cmd
  @echo on
)
