#! /bin/bash

# execute with 'source' command.

ANDROID_SDK_LOCATION=~/Android/Sdk
ANDROID_NDK_LOCATION=$ANDROID_SDK_LOCATION/ndk
ANDROID_NDK_VERSION=21.0.6113669

ANDROID_SDK_TOOLS_PATH=$ANDROID_SDK_LOCATION/tools:$ANDROID_SDK_LOCATION/platform-tools
ANDROID_NDK_PATH=$ANDROID_NDK_LOCATION/$ANDROID_NDK_VERSION
PATH=$ANDROID_SDK_TOOLS_PATH:$ANDROID_NDK_PATH:$PATH

cd $HOME
clear
